# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Kalium"
license = "MIT"
licenselink = "https://github.com/CountMurphy"
description = "Kalium theme forked from Bleak"
homepage = "https://random-hackery.net/"
tags = ["ghost", "minimal"]
features = ["", ""]
min_version = 0.15

[author]
  name = "Sarif"
  homepage = "http://random-hackery.net"

# If porting an existing theme
[original]
  name = "Peter Amende"
  homepage = "https://github.com/zutrinken"
  repo = "https://github.com/zutrinken/bleak"
